### ISSUE TITLE
MotoWaves not processing

### ISSUE THREAD

**Issue by Xekresis** [reiryuki/Moto-Waves-G-5G-Plus-Maxx-Audio-Magisk-Module#1]
Hey there,
I am having a problem where MotoWaves is installing fine but it's not processing anything. This happens on every rom by one developer that doesn't want to fix the issue so I am trying to do something. I am on OOS 10.3.8 OOS Q on my Redmi Note 9S (curtana). 
[logcat_02-05-2021_22-35-58.txt](https://github.com/reiryuki/Moto-Waves-G-5G-Plus-Maxx-Audio-FX-Magisk-Module/files/5935485/logcat_02-05-2021_22-35-58.txt)

**Comment by reiryuki** [comment]
All system and vendor "audio_effects" files needed

If you are in A11, read attention section
